# Generated by Django 3.2 on 2025-04-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20250423_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='', verbose_name='Картинки'),
        ),
    ]
