# Generated by Django 3.2 on 2025-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='changed_user',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.JSONField(default=dict, verbose_name='Картинки'),
        ),
    ]
