# Generated by Django 3.2 on 2025-05-29 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20250524_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('use_case', models.CharField(max_length=255, verbose_name='Сценарий использования')),
                ('checkpoints', models.JSONField(verbose_name='Пункты проверки')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
            ],
            options={
                'verbose_name': 'Чек-лист',
                'verbose_name_plural': 'Чек-листы',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('safety_management', 'Safety management'), ('training_registers', 'Реестры по обучению'), ('incidents', 'Инциденты и расследования'), ('other', 'Другие документы')], max_length=50, verbose_name='Категория')),
                ('topics', models.CharField(blank=True, max_length=255, verbose_name='Темы')),
                ('file_url', models.URLField(verbose_name='Ссылка на файл')),
                ('valid_from', models.DateField(verbose_name='Дата начала действия')),
                ('valid_to', models.DateField(verbose_name='Дата окончания действия')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('topic', models.CharField(max_length=255, verbose_name='Категория')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='LegalAct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('law', 'Закон'), ('code', 'Кодекс'), ('npa', 'НПА'), ('gost', 'ГОСТ')], max_length=50, verbose_name='Тип')),
                ('document_number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('date_of_issue', models.DateField(verbose_name='Дата выпуска')),
                ('relevance_status', models.CharField(choices=[('actual', 'Актуален'), ('obsolete', 'Устарел')], max_length=20, verbose_name='Статус актуальности')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Нормативный акт',
                'verbose_name_plural': 'Нормативные акты',
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('speakers', models.CharField(max_length=255, verbose_name='Спикеры')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Прошёл'), ('recording', 'Запись')], max_length=20, verbose_name='Статус')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название инструктажа')),
                ('instruction_type', models.CharField(choices=[('introductory', 'Вводный'), ('primary', 'Первичный'), ('repeated', 'Повторный'), ('targeted', 'Целевой'), ('unscheduled', 'Внеплановый')], max_length=50, verbose_name='Тип инструктажа')),
                ('format', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('pdf', 'PDF')], max_length=20, verbose_name='Формат')),
                ('category', models.CharField(choices=[('introductory', 'Вводный инструктаж'), ('primary_workplace', 'Первичный на рабочем месте'), ('repeated', 'Повторный'), ('unscheduled', 'Внеплановый'), ('targeted', 'Целевой')], default='introductory', max_length=50, verbose_name='Категория')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Встроенный текст')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Внешняя ссылка')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('related_checklists', models.ManyToManyField(blank=True, related_name='instructions', to='news.Checklist', verbose_name='Связанные чек-листы')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='instructions', to='news.Document', verbose_name='Связанные документы')),
            ],
            options={
                'verbose_name': 'Инструктаж',
                'verbose_name_plural': 'Инструктажи',
                'ordering': ['-created_date'],
            },
        ),
    ]
