# Generated by Django 3.2 on 2025-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20250529_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/instructions/', verbose_name='Файл'),
        ),
    ]
