# Generated by Django 3.2 on 2025-05-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20250529_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='content',
        ),
        migrations.AddField(
            model_name='instruction',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
