# Generated by Django 3.2 on 2025-05-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20250529_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
    ]
