# Generated by Django 3.2 on 2025-05-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('main_laws', 'Основные законы и кодексы'), ('RLA', 'Нормативно-правовые акты (НПА)'), ('rules_and_requirements', 'Правила и требования по охране труда'), ('tech_standarts', 'Технические регламенты и стандарты'), ('changes_and_updates', 'Изменения и обновления'), ('letters', 'Письма и разъяснения госорганов')], max_length=50, verbose_name='Категория')),
                ('topics', models.CharField(blank=True, max_length=255, verbose_name='Темы')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на файл')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/documents/', verbose_name='Файл')),
                ('valid_from', models.DateField(verbose_name='Дата начала действия')),
                ('valid_to', models.DateField(verbose_name='Дата окончания действия')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
