# Generated by Django 3.2 on 2025-05-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_law'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('construction', 'Строительство'), ('mining', 'Горная промышленность'), ('neftegas', 'Нефтегаз')], max_length=50, verbose_name='Категория')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('valid_from', models.DateField(verbose_name='Дата начала действия')),
            ],
            options={
                'verbose_name': 'Обучение',
                'verbose_name_plural': 'Обучение',
            },
        ),
        migrations.AlterModelOptions(
            name='law',
            options={'verbose_name': 'Законодательство', 'verbose_name_plural': 'Законодательства'},
        ),
    ]
