# Generated by Django 3.2 on 2025-05-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20250530_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Ближайшие вебинары (анонс)'), ('completed', 'Прошедшие вебинары (архив)'), ('recording', 'Сейчас идет')], max_length=20, verbose_name='Статус'),
        ),
    ]
