# Generated by Django 3.2 on 2025-05-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_webinar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='speakers_profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия'),
        ),
    ]
