# Generated by Django 3.2 on 2025-05-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20250530_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='image',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Картинки'),
        ),
    ]
