# Generated by Django 3.2 on 2025-05-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_webinar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='image',
            field=models.ImageField(blank=True, default=dict, null=True, upload_to='', verbose_name='Картинки'),
        ),
    ]
