# Generated by Django 3.2 on 2025-05-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_webinar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='special',
            field=models.CharField(blank=True, choices=[('certificate', 'Сертификат'), ('live', 'Только в прямом эфире'), ('free', 'Бесплатно')], max_length=20, null=True, verbose_name='Cпециальное'),
        ),
    ]
