# Generated by Django 3.2 on 2025-05-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_webinar_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='image',
        ),
    ]
