# Generated by Django 3.2 on 2025-06-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_webinar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('recording', 'Сейчас идет'), ('scheduled', 'Ближайшие вебинары (анонс)'), ('completed', 'Прошедшие вебинары (архив)')], max_length=20, verbose_name='Статус'),
        ),
    ]
