# Generated by Django 3.2 on 2025-06-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_webinar_status'),
        ('news', '0024_alter_article_changed_user'),
    ]

    operations = [
    ]
