# Generated by Django 3.2 on 2025-06-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_merge_20250602_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='changed_user',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Внесший изменения'),
        ),
    ]
