# Generated by Django 3.2 on 2025-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_article_changed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Теги'),
        ),
    ]
