# Generated by Django 3.2 on 2025-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_law_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='tags',
        ),
        migrations.AddField(
            model_name='law',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_law', to='news.Tag'),
        ),
    ]
