# Generated by Django 3.2 on 2025-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20250602_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
