# Generated by Django 3.2 on 2025-06-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_document_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='author_profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия автора'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, choices=[('organisation ', 'Организация охраны труда'), ('PPE', 'СИЗ и рабочая форма'), ('documents', 'Документы и оформление'), ('inspections ', 'Проверки и ответственность'), ('accidents', 'Несчастные случаи и расследования')], max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='faq',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
    ]
