# Generated by Django 3.2 on 2025-06-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_remove_faq_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='topic',
        ),
    ]
